# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='ur_robotiq_gripper',
    version='0.1.0',
    description='A simple and easy to use python module to control the Robotiq Hand-E gripper attached to a Universal Robots robot arm.',
    python_requires='==3.*,>=3.6.0',
    author='Fabian Freihube',
    author_email='fabi@davincikitchen.com',
    packages=['ur_robotiq_gripper'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
)
